# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: "YOUR_USERNAME"
  CLOUD_SQL_PASSWORD: "YOUR_PASSWORD"
  CLOUD_SQL_DATABASE_NAME: "DATABASE_NAME"
  CLOUD_SQL_CONNECTION_NAME: "CLOUD_SQL_INSTANCE_NAME"
# [END gae_python37_cloudsql_config]
