# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: rohan
  CLOUD_SQL_PASSWORD: test1234
  CLOUD_SQL_DATABASE_NAME: demo
  CLOUD_SQL_CONNECTION_NAME: absolute-router-277623:us-central1:my-sql-instance
# [END gae_python37_cloudsql_config]
